### ISSUE TITLE
Calendar trigger app crashes when I click on browser for a sound option.

### ISSUE THREAD

**Issue by pzdawood** [rparkins999/CalendarTrigger#10] opened 2018-05-27 01:00 UTC
### Actual behaviour
When I open the calendar trigger opensource android app and click on new event class option . After that I created a new event class option .  I clicked on Event  start action(s)  for class option.   After that I open the show a notification and play a sound options . Then I click on browse for sound file option app suddenly crashes.
### How to reproduce
* Download the calendar trigger app from F-driod.
* Install this app.
* Open the calendar trigger app.
* Click on new event class option .
* Create a new event class.
* Click on event start actions for class option.
* Turn show a notification and play a sound on .
* Then click on browser for a sound file option app gets crash.
* Browser: calendar trigger.
* Version: 2.0
* Operating system: 7.1.2
### Recording of the bug
https://youtu.be/6UmLOUSAXE8

**Comment by rparkins999** [comment] 2018-05-27 20:53
The cause of this problem is an error which got into in the code which defaults to the directory last used by the internal file browser. It doesn't work correctly when the internal file browser has never before been used, in particular if you've newly installed the app. In my own tests, of course, it always had been used before on my real phone and on my emulated devices. I have a fix for this problem and I will put it into the github source as soon as I can. I'm not sure how to get it into the F-Droid built version - I think that they don't automatically rebuild for point releases so I may have to make it version 3.0.

**Comment by rparkins999** [comment] 2018-05-27 21:38
Now fixed in github release 2.2

**Comment by rparkins999** [comment] 2018-05-31 19:36
Fixed in release 2.2 which is now available in both github and f-droid, so I'm closing this one.

**Closed as completed by rparkins999** 2018-05-31 19:36 UTC
